### PR TITLE
Expand on the addon api

### PR DESCRIPTION
**Pull request by DogLoverPink**
Semi related to #43 

I would like to preface this by saying that I do not know what you had in mind for the addon API, and if this is not to your liking, just close the pr.

This pr would add many more addon api events, and would overall make it more powerful.
**Events Added:**

- OnTabCreate()
- OnTabClose()
- OnFileOpened(fileName)
- OnFileClosed(fileName)
- OnFileSave(fileName)
- OnPublish(url)
- OnQuickEdit(quickEditType) - quickEditType is an enum
- OnGenerate(generateType_ - generateType is an enum
- OnBackPackAdd(addedString)
- OnBackPackRemove(removedString)
- OnBackPackPaste(pastedString)
- OnCompletionAccept(acceptedCompletion)
- OnAddonInstall(addonName, addonAuthor, addonVersion)
- OnAddonUnInstall(addonName, addonAuthor, addonVersion)
- OnAddonUpdate(addonName, addonAuthor, addonVersion)
- OnSyntaxDisable()
- OnSyntaxChange(newSyntaxName)
- OnSiteOpen(name, url) - ex. parser, docs
- OnCheckForUpdates(currentVersion, latestVersion)
- OnExiting()

**This pr also (accidently) adds this, because I am bad at Git.**
Adds a new "Quick Edit" action that replaces all indenting tabs with a specified amount of spaces.
image

### CODE REVIEW

**Comment by DogLoverPink** [comment]
I just realized that this includes my previous commit as well. I don't know how to fix that.

**Comment by NotroDev** [comment]
Ohhh! I know I've said it a lot of times... but it's *so cool!* Thanks!
I'll review it tomorrow or another day.

**Comment by GliczDev** [comment]
Imo it should use [EventHandlers](https://learn.microsoft.com/pl-pl/dotnet/api/system.eventhandler?view=net-7.0) in SkEditorAPI interface

**Comment by GliczDev** [comment]
Imo it should use [EventHandlers](https://learn.microsoft.com/pl-pl/dotnet/api/system.eventhandler?view=net-7.0) in SkEditorAPI interface

**Comment by DogLoverPink** [comment]
Alright, I’ll work on it.

**Comment by DogLoverPink** [comment]
Oh, I thought that you were Notro. While it’s probably a good idea, I’ll wait for Notro to give feedback before changing things.

**Comment by NotroDev** [comment]
> Oh, I thought that you were Notro. While it’s probably a good idea, I’ll wait for Notro to give feedback before changing things.

Uh, I don't know about it. I created this event system for simplicity (it's based on a Unity's event system, which I used and liked). Event Handlers are better in some things, but I think I would prefer to stay with the current event system. Maybe I'll change it in a rewrite of the app. In my opinion, don't bother with this, because even if I want to change it, I'll do it.

**Pull request merged**
