### PR TITLE
README.md | Fixed Grammarly's additional writing issue

### PR DESCRIPTION
**Pull request by KwiatekMiki**

### CODE REVIEW

**Comment by GliczDev** [comment]
As i know, this extended support is no longer available, so it should be removed

**Comment by KwiatekMiki** [comment]
why?

**Comment by NotroDev** [comment]
> why?

https://github.com/NotroDev/SkEditorPlus/commit/20056c495c88dfa1830d0218c6d8d25e214abd7b

**Comment by KwiatekMiki** [comment]
oh ok

**Pull request closed without merging**
